make:
	##################################################################################
	# Make tar.gz archive of BlueGlass-XCursors-3D-0.4 directory in parent directory #
	# * to run it type - make  * for clean type - make clean                         #
	##################################################################################
	
	tar -zcvf ../BlueGlass-XCursors-3D-0.4.tar.gz ../Golden-XCursors-3D-0.8
	
clean:
	rm -f ../BlueGlass-XCursors-3D-0.4.tar.gz
	