alias s="sudo"
alias ll='ls -lhF --group-directories-first'
alias l.='ls -lhaF --group-directories-first'
alias l='ls -CF --group-directories-first'
alias la='ls -aCF --group-directories-first'
alias 7zip='7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on'
alias 7zipenc='7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p'
alias SDU='sudo apt-get clean && sudo apt-get update && sudo apt-get dist-upgrade'
alias SUG='sudo apt-get clean && sudo apt-get update && sudo apt-get upgrade'
alias M='python manage.py'
alias MR='python manage.py runserver'
alias MC='python manage.py collectstatic'
alias FXP='firefox -private'
alias FXS='firefox -safe-mode'
alias FXD='MOZILLA_DISABLE_PLUGINS=1 firefox'
alias FXPS='firefox -safe-mode -private'
alias FXPD='MOZILLA_DISABLE_PLUGINS=1 firefox -private'
alias FXSD='MOZILLA_DISABLE_PLUGINS=1 firefox -safe-mode'
alias FXAP='MOZILLA_DISABLE_PLUGINS=1 firefox -safe-mode -private'
alias FX='firefox'
