alias s='sudo'
alias ll='ls -lhF --group-directories-first'
alias l.='ls -lhaF --group-directories-first'
alias l='ls -CF --group-directories-first'
alias la='ls -aCF --group-directories-first'
alias 7zip='7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on'
alias 7zipenc='7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on -mhe=on -p'
alias AGC='sudo apt-get clean'
alias AGI='sudo apt-get install'
alias AGF='sudo apt-get -f install'
alias AGR='sudo apt-get remove'
alias AGP='sudo apt-get purge'
alias AGAC='sudo apt-get autoclean'
alias AGAR='sudo apt-get autoremove'
alias AGAP='sudo apt-get --purge autoremove'
alias SUG='sudo apt-get clean && sudo apt-get update && sudo apt-get upgrade'
alias SDU='sudo apt-get clean && sudo apt-get update && sudo apt-get dist-upgrade'
alias M='python manage.py'
alias MH='python manage.py shell'
alias MR='python manage.py runserver'
alias MC='python manage.py collectstatic'
alias MS='python manage.py syncdb'
alias MSA='python manage.py sqlall'
alias MSR='python manage.py sqlreset'
alias KM='kill -9 `ps axw | grep manage.py | grep -v grep | cut -d " " -f 1`'
alias FXP='firefox -private'
alias FXS='firefox -safe-mode'
alias FXD='MOZILLA_DISABLE_PLUGINS=1 firefox'
alias FXPS='firefox -safe-mode -private'
alias FXPD='MOZILLA_DISABLE_PLUGINS=1 firefox -private'
alias FXSD='MOZILLA_DISABLE_PLUGINS=1 firefox -safe-mode'
alias FXAP='MOZILLA_DISABLE_PLUGINS=1 firefox -safe-mode -private'
alias FX='firefox'
