[Icon Theme]
Name=blueprint-cursor-theme
Comment=blueprint-cursor-theme part of the blueprint theme
Inherits=gnome
DisplayDepth=32
Example=exec
LinkOverlay=link
LockOverlay=lockoverlay
ZipOverlay=zip
DesktopDefault=48
DesktopSizes=16,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,32
MainToolbarDefault=22
MainToolbarSizes=16,22,32
SmallDefault=20
SmallSizes=16,20,22,24
PanelDefault=48
PanelSizes=16,32,48
Directories=cursors

[cursors]
Size=16
